# Generated by Django 4.0.1 on 2022-01-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('endereco', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('cidade', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('senha', models.CharField(blank=True, max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
